POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Chimpi.T.Chompa",
  "name": "Chimpi",
  "password": "Testing1"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "",
  "name": "Chimpi",
  "password": "Testing1"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Chimpi.T.Chompa",
  "name": "Chimpi",
  "password": ""
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "Alpargata.Cosmica2",
  "name": "Alpargata",
  "password": "Testing2"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
"username": "Testing",
"name": "Tester",
"password": "Testing1"
}